name: Build Kiwi

on:
    push:
        branches: ["main"]

permissions:
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out a branch
              uses: actions/checkout@v3

            - name: Initialize NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: "20.11.0"
                  cache: "yarn"

            - name: Initialize the build environment
              run: yarn

            - name: Build Kiwi
              run: yarn build

            - name: Upload build results
              uses: actions/upload-artifact@v4
              with:
                  name: Kiwi
                  path: ./buid
                  compression-level: 9
