name: Build Kiwi

on:
    push:
        branches: ['main']

permissions:
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout a branch
              uses: actions/checkout@v3

            - name: Initialize pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 'latest'

            - name: Initialize NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: '20.17.0'
                  cache: 'pnpm'

            - name: Initialize the build environment
              run: pnpm install

            - name: Build Kiwi
              run: pnpm run build

            - name: Upload build results
              uses: actions/upload-artifact@v4
              with:
                  name: Kiwi
                  path: ./dist
                  compression-level: 9
